"""Write input/fanout.trig and links/fanout.ttl: one shape, 100 violations,
spread over 50 data graphs that are all named in one link."""
GRAPHS, PER_GRAPH = 50, 2
head = """@prefix ex: <http://example.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

# Generated by gen-fanout.py. One property shape, 100 negative readings in 50 data graphs.
ex:shapes\\/fanout {
    ex:MeterShape a sh:NodeShape ; sh:targetClass ex:Meter ; sh:property ex:MeterReadingShape .
    ex:MeterReadingShape a sh:PropertyShape ; sh:path ex:reading ; sh:minInclusive 0 .
}
"""
with open("input/fanout.trig", "w") as f:
    f.write(head)
    for g in range(1, GRAPHS + 1):
        rows = "".join(f"    ex:meter{g}-{i} a ex:Meter ; ex:reading -{i} .\n" for i in range(1, PER_GRAPH + 1))
        f.write(f"ex:data\\/fanout-{g:02d} {{\n{rows}}}\n")
with open("links/fanout.ttl", "w") as f:
    graphs = ", ".join(f"ex:data\\/fanout-{g:02d}" for g in range(1, GRAPHS + 1))
    f.write("@prefix rsx: <http://rdf4j.org/shacl-extensions#> .\n@prefix ex: <http://example.org/> .\n\n"
            "# Generated by gen-fanout.py. Post into rdf4j:SHACLShapeGraph.\n"
            f"ex:link\\/fanout a rsx:DataAndShapesGraphLink ;\n    rsx:dataGraph {graphs} ;\n    rsx:shapesGraph ex:shapes\\/fanout .\n")
